from typing import List, Protocol


class VCSClient(Protocol):

    def get_token_username(self) -> str: ...
    def get_mr_notes(self, mr_iid: str) -> List[dict]: ...
    def post_mr_note(self, mr_iid: str, message: str) -> None: ...
