messages:
  - "🎄 Happy New Year! Wishing you lots of commits without bugs! 🐞"
  - "✨ May your pipelines always be green in the New Year! ✅"
  - "🥂 Cheers to new features, fewer merge conflicts, and lots of success!"
  - "🎅 Santa says: keep coding, keep shipping, keep smiling! 🚀"
cards:
  - "https://s3.getstickerpack.com/storage/uploads/sticker-pack/pepe-the-frog-1/sticker_30.png?45f2f168a42095ed37c40728e65f957f&d=100x100"
  - "https://s3.getstickerpack.com/storage/uploads/sticker-pack/pepe-the-frog-1/sticker_25.png?45f2f168a42095ed37c40728e65f957f&d=100x100"
  - "https://img-13.stickers.cloud/packs/cafe5455-06c6-40ea-a243-809a8913c216/webp/animated/e516ea6b-5f32-4919-b432-74b2cd0c38f9.webp"
